# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: sdkman
before:
  hooks:
builds:
  - id: "sdk"
    main: ./main.go
    binary: sdk
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      # support i386 after https://github.com/scylladb/go-set/issues/16 release
      #- 386
    goarm:
      - 5
      - 6
      - 7
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ldflags:
      - > 
          -s 
          -w 
          -X github.com/palindrom615/sdkman/cmd.version={{.Version}} 
          -X github.com/palindrom615/sdkman/cmd.commit={{.Commit}} 
          -X github.com/palindrom615/sdkman/cmd.date={{.Date}} 
          -X github.com/palindrom615/sdkman/cmd.builtBy=goreleaser`.
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - tap:
      owner: palindrom615
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/palindrom615/sdkman"
    description: "A tool for managing parallel versions of multiple Software Development Kits"
scoop:
  bucket:
    owner: palindrom615
    name: scoop-bucket
  homepage: "https://github.com/palindrom615/sdkman"
  license: Apache License 2.0
  description: "A tool for managing parallel versions of multiple Software Development Kits"
